# dotCMS Production Environment Configuration
# This file contains environment-specific values for dotCMS deployment

# Global configuration
global:
  environment: prod
  domain: dotcms.company.com
  namespace: dotcms-prod

# dotCMS specific configuration
dotcms:
  image:
    repository: dotcms/dotcms
    tag: "5.3.8"  # Pin to specific stable version
    pullPolicy: IfNotPresent
  
  replicas: 3
  
  resources:
    requests:
      memory: "4Gi"
      cpu: "2000m"
    limits:
      memory: "8Gi"
      cpu: "4000m"
  
  # Production specific settings
  config:
    # Disable debug mode for production
    debug: false
    
    # Database configuration
    database:
      host: postgres-prod-cluster
      port: 5432
      name: dotcms_prod
      username: dotcms
      password: ${DB_PASSWORD}  # Use secret reference
      ssl: true
    
    # Elasticsearch configuration
    elasticsearch:
      host: elasticsearch-prod-cluster
      port: 9200
      cluster: dotcms-prod
      ssl: true
    
    # License configuration
    license:
      type: "production"
      key: ${LICENSE_KEY}  # Use secret reference
    
    # Cache configuration
    cache:
      enabled: true
      type: "redis"
      host: redis-prod-cluster
      port: 6379
      ssl: true

# Service configuration
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: dotcms.company.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: dotcms-prod-tls
      hosts:
        - dotcms.company.com

# Persistence configuration
persistence:
  enabled: true
  storageClass: "fast-ssd"
  size: 200Gi
  accessMode: ReadWriteOnce

# Monitoring configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true
  alerting:
    enabled: true

# Logging configuration
logging:
  level: WARN
  format: json

# Security configuration
security:
  enabled: true
  ssl:
    enabled: true
  authentication:
    enabled: true
  networkPolicies:
    enabled: true

# High Availability configuration
ha:
  enabled: true
  podDisruptionBudget:
    enabled: true
    minAvailable: 2
  horizontalPodAutoscaler:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

# Backup configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: "30d"
