# dotCMS Staging Environment Configuration
# This file contains environment-specific values for dotCMS deployment

# Global configuration
global:
  environment: staging
  domain: staging.dotcms.local
  namespace: dotcms-staging

# dotCMS specific configuration
dotcms:
  image:
    repository: dotcms/dotcms
    tag: "stable"
    pullPolicy: IfNotPresent
  
  replicas: 2
  
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"
  
  # Staging specific settings
  config:
    # Disable debug mode for staging
    debug: false
    
    # Database configuration
    database:
      host: postgres-staging
      port: 5432
      name: dotcms_staging
      username: dotcms
      password: staging_password
    
    # Elasticsearch configuration
    elasticsearch:
      host: elasticsearch-staging
      port: 9200
      cluster: dotcms-staging
    
    # License configuration
    license:
      type: "staging"
    
    # Cache configuration
    cache:
      enabled: true
      type: "redis"
      host: redis-staging
      port: 6379

# Service configuration
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: staging.dotcms.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: dotcms-staging-tls
      hosts:
        - staging.dotcms.local

# Persistence configuration
persistence:
  enabled: true
  storageClass: "fast-ssd"
  size: 50Gi
  accessMode: ReadWriteOnce

# Monitoring configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true

# Logging configuration
logging:
  level: INFO
  format: json

# Security configuration
security:
  enabled: true
  ssl:
    enabled: true
  authentication:
    enabled: true
